### ISSUE TITLE
 [Guilds][java 16] Could not download Artifact{groupId='org.jetbrains.kotlin', artifactId='kotlin-stdlib', version='1.4.32', repoBaseURL='maven'}

### ISSUE THREAD

**Issue by hkkongou** [guilds-plugin/Guilds#442]
## Description

when guilds plugin start up on java 16, it show the following errors
```
[10:45:46 ERROR]: [Guilds] Could not download Artifact{groupId='org.jetbrains.kotlin', artifactId='kotlin-stdlib', version='1.4.32', repoBaseURL='maven'}
java.util.concurrent.CompletionException: java.lang.ExceptionInInitializerError
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1769) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
        at me.bristermitten.pdm.DependencyLoader.loadDependency(DependencyLoader.java:47) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        ... 8 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @5bcf99e0
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
        at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
        at me.bristermitten.pdm.util.ClassLoaderReflection.<clinit>(ClassLoaderReflection.java:33) ~[?:?]
        at me.bristermitten.pdm.DependencyLoader.loadDependency(DependencyLoader.java:47) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        ... 8 more
[10:45:46 ERROR]: [Guilds] Could not download Artifact{groupId='org.jetbrains.kotlin', artifactId='kotlin-stdlib-jdk8', version='1.4.32', repoBaseURL='maven'}
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: Could not initialize class me.bristermitten.pdm.util.ClassLoaderReflection
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1769) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.helpAsyncBlocker(ForkJoinPool.java:1145) ~[?:?]
        at java.util.concurrent.ForkJoinPool.helpAsyncBlocker(ForkJoinPool.java:3160) ~[?:?]
        at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1883) ~[?:?]
        at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2113) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at me.bristermitten.pdm.DependencyManager.lambda$download$3(DependencyManager.java:147) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class me.bristermitten.pdm.util.ClassLoaderReflection
        at me.bristermitten.pdm.DependencyLoader.loadDependency(DependencyLoader.java:47) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        ... 17 more
[10:45:46 ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] java.lang.NoClassDefFoundError: Could not initialize class me.bristermitten.pdm.util.ClassLoaderReflection initializing Guilds v3.5.5.8 (Is it up to date?)
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: Could not initialize class me.bristermitten.pdm.util.ClassLoaderReflection
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1769) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class me.bristermitten.pdm.util.ClassLoaderReflection
        at me.bristermitten.pdm.DependencyLoader.loadDependency(DependencyLoader.java:47) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        ... 8 more
```

## Expected Behavior

there should be no error and in java 11, no error

## Actual Behavior

the error appear every time when the server start up and i have tested with only 1 guilds installed

## Possible Fix

idk :( 
not sure is this a problem with java 16 support or not or just a non related bug

## Steps to Reproduce

1.start up server
2.wait
3.
4.

## Context

it only show the error, the system should not be affected, most of the core functions are working

## Your Environment

* Guilds version
* 3.5.5.8
* MC Version
* 1.16.5 purpur 1111
* Plugin List
* guilds
![image](https://user-images.githubusercontent.com/61608872/118346247-a092c200-b56c-11eb-9ee0-283e447d3b7d.png)

**Comment by HauserGrim** [comment]
+1
After upgrade java to 16
https://pastebin.com/aZ6MnuQ4

**Comment by HauserGrim** [comment]
Using dev build when compiling will probably fix this.
https://github.com/JetBrains/kotlin/commit/b27dd8e3fe0

**Comment by HauserGrim** [comment]
Perhaps some of this will help fix: 
https://youtrack.jetbrains.com/issue/KT-44266#focus=Comments-27-4643863.0-0 
https://github.com/JetBrains/kotlin/commit/b27dd8e3fe0

**Comment by HauserGrim** [comment]
@hkkongou 
Try --illegal-access=permit flag

**Comment by hkkongou** [comment]
> @hkkongou
> Try --illegal-access=permit flag

what is that
I am not a developer

**Comment by HauserGrim** [comment]
> > @hkkongou
> > Try --illegal-access=permit flag
> 
> what is that
> I am not a developer

In server startup file (start.bat / start.sh)
For example java Xms300M -Xmx2000M --illegal-access=permit -Dfile.encoding=UTF-8 -jar server.jar

**Comment by darbyjack** [comment]
Hey guys! I am totally aware of this issue and it lies from one of the dependencies that Guilds uses for library downloads. That being said, I have reached out to the developer of that library and am hoping to come to a solution soon.

**Comment by darbyjack** [comment]
Fixed via https://github.com/guilds-plugin/Guilds/commit/d3dc4c6e1df9cfc0b4db399be1e5d5c3474add13
